### ISSUE TITLE
Compile errors with cxx.std = latest

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/sqlite_orm#1]
Hi @boris-kolpackov 

with this library I get compile errors with specific compilers (versions), when compiling with C++20 (or later).

In my `root.build` I specified to always use `cxx.std = latest`. For some compilers this results in picking a not feature-complete C++20 standard. `sqlite_orm` however uses some of the feature which are missing in those compilers, specifically [the constructor from iterators](https://en.cppreference.com/w/cpp/string/basic_string_view/basic_string_view) of `std::string_view`.

Now, the library itself distinguishes if it was compiled with C++14, 17 or 20 and uses features depending on the configured standard (e.g. see the problematic lines [here](https://github.com/fnc12/sqlite_orm/blob/68ec24830dd0131c4f223d8d60d1b1d914e8cefa/include/sqlite_orm/sqlite_orm.h#L12682)). In the upstream build system the library consumer must actively choose to enable C++17 / 20 support, the default is C++14. So it is theoretically possible to compile this library successfully for the compilers for which it currently fails in my build2 builds (using C++14 / 17).

I get that I could just set the standard to `cxx.std  = 14`, however I really would like to support also the C++17 / 20 features of the library. Is there a idiomatic build2 way of doing this? Does it make sense to do something like this:

```cpp
config [string] config.libsqlite_orm.cxx_std ?= latest
cxx.std = $config.libsqlite_orm.cxx_std
```

Here's a sample build on `bdep ci` which fails, because of the missing C++20 feature:

https://ci.cppget.org/@a20db9d4-30ab-427b-8c64-b43032550273/libsqlite_orm/1.8.1-a.0.20230212191919.309b51ba6296/log/macos_12-clang_13.1-static_O3/public/0.15.0/test

**Comment by boris-kolpackov** [comment]
In `build2` we've settled on the following idiomatic arrangement:

1. The library specifies `cxx.std = latest` in its `root.build`. 

2. The user can override the standard for the *entire build* with `config.cxx.std=xxx`.

The "entire build" part above is important: while some compiler/versions on some platforms may support mixing standards during the full moon, we don't really have time or energy to play such games. So, as a result, we strongly discourage libraries specifying anything other than `latest` (which is essentially our common default) in their `root.build`.

Now what to do about this specific case. I think there are two options:

The easiest is to simply exclude the CI builds for compilers that are not sufficiently C++20 with a comment that it can be used with C++14/17 if desired.

The other option is to override the C++ standard with `config.cxx.std` for such CI builds. This will be possible in the upcoming 0.16.0 release.

**Comment by Rookfighter** [comment]
Alright thanks. So I changed the `requires` part of the manifests to `requires: c++20`. However, I still get the same error with some clang builds (see [here](https://ci.cppget.org/@fdbd75e1-68df-4462-9f5e-30f318e06ba0/libsqlite_orm/1.8.1-a.0.20230213182304.01269b59a789/log/macos_12-clang_13.1-static_O3/public/0.15.0/test)), so I guess that is not sufficient to tell bdep ci to only build with compilers with full C++20 support. Do you have any suggestions?

**Comment by boris-kolpackov** [comment]
Yes, [`requires`](https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-requires) is (for now) only for documentation. You will need to exclude these build configurations using [`builds`](https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-builds) and/or [`build-exclude`](https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-include-exclude).

For example, you could only build with the latest versions of each compiler:

```
builds: latest
```

**Comment by Rookfighter** [comment]
Worked for me  :+1:
