### ISSUE TITLE
Issues with submitted `1.8.1` packages

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/sqlite_orm#2]
I've noticed a couple of issues with the submitted `1.8.1` packages:

1. The project name (`project` value in `manifest`) is surprising `SQLiteORM`. Normally we use the upstream project name, the same as repository name (`sqlite_orm` in this case). I think it makes sense to fix this early since this name is used as a directory for ownership information and changing it later will be messy.

2. `license: AGPL/MIT` is not canonical. After looking at upstream they license it as AGPL-2.0 or `MIT` after a payment (what nonsense!). I would just make it `license: AGPL-3.0-only` (especially seeing that that's the only license file included). For details, see https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-license

3. In the library `buildfile` there is this questionable code:

```
switch $cxx.target.class
{
    case 'windows'
    {
        if ($cxx.id == 'msvc')
        {
            platform_coptions += /EHsc /bigobj /Zc:__cplusplus /MP
            platform_poptions += -D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
        }
    }
}

cxx.coptions += $platform_coptions
cxx.poptions += "-I$out_inc" "-I$src_inc" $platform_poptions

lib{sqlite_orm}:
{
  cxx.export.coptions = $platform_coptions
  cxx.export.poptions = "-I$out_inc" "-I$src_inc" $platform_poptions
  cxx.export.libs = $intf_libs
}
```

Nothing is being compiled here (it's a header-only library) so setting `cxx.[pc]options` is pointless. There is also no such thing as `cxx.export.coptions`.

Also, even if there were source files, forcing these options is a bad idea, for details, see: https://github.com/build2/HOWTO/blob/master/entries/compile-options-in-buildfile.md

Even exporting `-D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING` is strictly speaking should not be done since you are making a decision for the user about which warnings they should have suppressed. But I guess you can keep it if it's really necessary seeing that we are in the MSVC land and the expectations are already low.

I think this `buildfile` should be reduced to just this:

```
import intf_libs = libsqlite3%lib{sqlite3}

lib{sqlite_orm}: hxx{**}
lib{sqlite_orm}: $intf_libs

out_inc = [dir_path] $out_root/include/
src_inc = [dir_path] $src_root/include/

platform_poptions =
switch $cxx.target.class
{
    case 'windows'
    {
        if ($cxx.id == 'msvc')
        {
            platform_poptions += -D_SILENCE_CXX17_CODECVT_HEADER_DEPRECATION_WARNING
        }
    }
}

lib{sqlite_orm}:
{
  cxx.export.poptions = "-I$out_inc" "-I$src_inc" $platform_poptions
  cxx.export.libs = $intf_libs
}

hxx{*}:
{
  install.subdirs = true
}
```

4. In both the examples and tests packages, there is the `/TP` option which shouldn't be there.

5. This is a minor nit, but I will mention it for completeness: when the tests are external, it's a good idea to include a smoke test with the library itself that verifies that things are at least functional (i.e., header can be included, library linked, basic API functions can be called).

I think it makes sense to fix these before publishing so I am going to go ahead and drop the submission from the queue so that you can resubmit with new project name.

**Comment by Rookfighter** [comment]
Alright thanks! Makes totally sense regarding the `buildfile`, I guess next time I should think a bit more about what the build is supposed to do and not just copy whatever upstream is doing :+1:

Regarding point 1 (project name): upstream uses `sqlite_orm` in its include path, as header name, as namespace and as target name in CMake. However, in the docs (README / Website) the library is always referred to as `SQLite ORM`. So my question is: should the project name typically match the header name / include directory / namespace rather than the name used in docs? There are many examples where this differs, e.g. OpenCV (namespace `cv`, include directory `opencv2`) or ZeroMQ (library `libzmq`, header name `zmq`). Is there a rule of thumb?

Regarding point 5 (smoketest): Are the external tests / examples packages not smoke tests themselves? I mean they only compile / link / run when the main library package correctly exports its headers and libraries. What's the benefit of an internal smoketest over the external tests?

**Comment by boris-kolpackov** [comment]
> Is there a rule of thumb?

Yes, the rule of thumb is to use the upstream `git` repository name. The idea behind the `project` name is to group related packages in multi-package projects/repositories. In such cases, the `git` repository name is almost always named after the "overall" project.

> What's the benefit of an internal smoketest over the external tests?

External tests packages are not downloaded/built by default unless requested explicitly. So if a user uses your library and wishes to run tests, then unless they explicitly build the tests packages, the only tests that will run are the bundled ones. There are plans to automatically suggest downloading/building the tests packages if the user performs the `tests` operation, but that's still a TODO. (Note that CI has extra logic to download/build external tests, if present.)

**Comment by Rookfighter** [comment]
Thanks, so would moving the examples package into the main package (instead of being a external package) be a sufficient smoke test? The examples do not have additional external dependencies. The examples are not executed as "tests" though.

**Comment by boris-kolpackov** [comment]
Yes, that's another option.

**Comment by boris-kolpackov** [comment]
A couple of notes on the resubmitted packages:

1. The `examples/` subproject is missing `exe{*}: test = true` (currently doing `b test` from root of the library results in "nothing to test").

2. The `install` module is unnecessary in `examples/build/booststrap.build`

These kinds of easy to forget details is the reason why I personally prefer to start with `bdep new`.

3. The `license` is still `AGPL/MIT` in the `-tests` package.

I am going to publish the packages but feel free to submit a revision with the fixes.

**Comment by Rookfighter** [comment]
Thanks again. I guess there was a misunderstanding from my side regarding point 1. Fixed all the mentioned issues in the latest revision.
